name: Build Firmware
on: 
  push:
    branches: 
      - 'main'
    paths:
      - 'src/*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - uses: bazhenov/action-avr-make@v1.0
      - name: Create Build Directory & move hex file
        run: mkdir -p build && mv Feuille64Midi.hex build/
      - name: Push to build branch
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: self
          BRANCH: build
          FOLDER: build
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
